[package]
edition = "2021"
name = "zg-git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd_lib = "1.3.0"


[[bin]]
name = "zg-git"
path = "src/bin/main.rs"